name: deploy website

on:
  push:
    branches:
      - main
      - dev
      - test/*
  pull_request_target:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  

      - name: Install dependencies
        run: npm ci

      - name: Pull Vercel environment variables
        run: |
          npx vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Build project with Vercel
        run: npx vercel build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: Determine deployment environment
        id: deploy_env
        run: |
          if [ "${{ github.ref }}" == 'refs/heads/main' ]
          then
              echo "vercel-args=--prod --prebuilt" >> $GITHUB_OUTPUT
              echo "vercel-domain=joyfulfrugalista-web.vercel.app" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == 'refs/heads/dev' ]] || [[ "${{ github.ref }}" == refs/heads/test/* ]]
          then
              echo "vercel-args=--prebuilt" >> $GITHUB_OUTPUT
              echo "vercel-domain=demo.lastoccultism.com" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25.2.0
        with:
          vercel-cli: vercel
          vercel-version: lastest
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ steps.deploy_env.outputs.vercel-args }}
          alias-domains: ${{ steps.deploy_env.outputs.vercel-domain }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
